# Recursive-Shortest-Path task (no load_graph in tools)

data: {}

server:
  base_url: "http://localhost"
  ports: 1234

generation:
  model: meta-llama/Llama-3.3-70B-Instruct
  temperature: 0.2
  top_p: 0.9

tool:
  schema_path: "external_tools/tool_schemas.yaml"
  handler: ShortestPathGame

template:
  dir: "templates"
  system_prompt_path: "system_prompt.jinja"
  user_prompt_path: "user_prompt.jinja"
  core_loop:
    - call_type: "think"
      additional_args: {}
      next_template_path: "thinking_response.jinja"
    - call_type: "action"
      additional_args:
        tools_avail: [inspect, move, submit]
        retry_limit: 1
      next_template_path: "action_response.jinja"

verifier:
  type: none

# graph-generation parameters
base_nodes: 4
max_edges: 2
recursion_depth: 2
weight_range: [1.0, 5.0]
seed: 42
