# Recursive-Shortest-Path task
data: {}                  # ← no external dataset; we generate graphs on the fly

server:                  
  base_url: http://localhost
  ports: 8088

generation:
  model: meta-llama/Llama-3.3-70B-Instruct
  temperature: 0.2
  top_p: .9

tool:
  schema_path: "external_tools/tool_schemas.yaml"
  handler: ShortestPathGame        # <— our new Game class

template:
  dir: "templates"
  system_prompt_path: "system_prompt.jinja"
  user_prompt_path: "user_prompt.jinja"
  core_loop:
    - call_type: think
      additional_args: {}
      next_template_path: thinking_response.jinja
    - call_type: action
      additional_args:
        tools_avail: [observe, move, submit_solution]
        retry_limit: 1
      next_template_path: action_response.jinja

verifier:
  type: tool
  tool_name: verify

# Parameters that will be injected into the game handler
graph_params:
  base_nodes: 6
  max_edges: 3
  recursion_depth: 0
  weight_choices: [1.0, 2.0]
  seed: 42
